"""add_fields_to_diary_version

Revision ID: 9a77b00fc3d1
Revises: e1886c51bcd1
Create Date: 2026-08-10 15:18:17.914637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a77b00fc3d1'
down_revision: Union[str, Sequence[str], None] = 'e1886c51bcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_versions', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('diary_versions', sa.Column('paragraphs', sa.JSON(), nullable=True))
    op.add_column('diary_versions', sa.Column('evidence_input_ids', sa.JSON(), nullable=True))
    op.alter_column('diary_inputs', 'storage_url', existing_type=sa.String(length=512), nullable=True)
    op.drop_constraint('uq_user_date', 'diary_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_date', 'diary_sessions', ['user_id', 'diary_date'])
    op.alter_column('diary_inputs', 'storage_url', existing_type=sa.String(length=512), nullable=False)
    op.drop_column('diary_versions', 'evidence_input_ids')
    op.drop_column('diary_versions', 'paragraphs')
    op.drop_column('diary_versions', 'content')
    # ### end Alembic commands ###
