"""Initial schema

Revision ID: e1886c51bcd1
Revises:
Create Date: 2026-08-06 13:14:35.116306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1886c51bcd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('result_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_agent_logs_trace_id'), 'agent_logs', ['trace_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('consent_scope', sa.JSON(), nullable=True),
    sa.Column('avatar_id', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('counsel_sessions',
    sa.Column('counsel_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('referenced_diary_ids', sa.JSON(), nullable=True),
    sa.Column('safety_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('counsel_id')
    )
    op.create_table('diary_sessions',
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('diary_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('user_id', 'diary_date', name='uq_user_date')
    )
    op.create_index(
        'ix_diary_sessions_user_status_date',
        'diary_sessions',
        ['user_id', 'status', 'diary_date'],
        unique=False,
    )
    op.create_table('diary_chats',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('chat', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diary_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('diary_inputs',
    sa.Column('input_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('storage_url', sa.String(length=512), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diary_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('input_id')
    )
    op.create_table('diary_versions',
    sa.Column('version_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('emotion_tags', sa.JSON(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diary_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(
        'ix_diary_versions_session_approved_created',
        'diary_versions',
        ['session_id', 'approved', 'created_at'],
        unique=False,
    )
    op.create_table('location_messages',
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diary_sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('avatar_videos',
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('version_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_url', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['diary_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatar_videos')
    op.drop_table('location_messages')
    op.drop_index('ix_diary_versions_session_approved_created', table_name='diary_versions')
    op.drop_table('diary_versions')
    op.drop_table('diary_inputs')
    op.drop_table('diary_chats')
    op.drop_index('ix_diary_sessions_user_status_date', table_name='diary_sessions')
    op.drop_table('diary_sessions')
    op.drop_table('counsel_sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_agent_logs_trace_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
